spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${T_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${T_DB_USERNAME}
    password: ${T_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

aes:
  secret:
    key: ${AES_SECRET_KEY}
  iv: ${AES_IV}


jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

server:
  address: 0.0.0.0
  port: 8080